units_dict = {
    # temperature
    'K':           {'to_SI':  {'f': lambda T: T,                                   'u': 'K'},
                    'to_cgs': {'f': lambda T: T,                                   'u': 'K'}},
    'C':           {'to_SI':  {'f': lambda T: T + 273.15,                          'u': 'K'},
                    'to_cgs': {'f': lambda T: T + 273.15,                          'u': 'K'}},
    'F':           {'to_SI':  {'f': lambda T: (T + 459.67) * (5 / 9),              'u': 'K'},
                    'to_cgs': {'f': lambda T: (T + 459.67) * (5 / 9),              'u': 'K'}},
    'R':           {'to_SI':  {'f': lambda T: T * (5 / 9),                         'u': 'K'},
                    'to_cgs': {'f': lambda T: T * (5 / 9),                         'u': 'K'}},
    # pressure
    'Pa':          {'to_SI':  {'f': lambda P: P,                                   'u': 'Pa'},
                    'to_cgs': {'f': lambda P: P*10,                                'u': 'barye'}},
    'bar':         {'to_SI':  {'f': lambda P: P*1e5,                               'u': 'Pa'},
                    'to_cgs': {'f': lambda P: P*1e5*10,                            'u': 'barye'}},
    'atm':         {'to_SI':  {'f': lambda P: P*101325,                            'u': 'Pa'},
                    'to_cgs': {'f': lambda P: P*101325*10,                         'u': 'barye'}},
    'psi':         {'to_SI':  {'f': lambda P: P*6894.757,                          'u': 'Pa'},
                    'to_cgs': {'f': lambda P: P*6894.757*10,                       'u': 'barye'}},
    'kgf/cm2':     {'to_SI':  {'f': lambda P: P*98066.52,                          'u': 'Pa'},
                    'to_cgs': {'f': lambda P: P*98066.52*10,                       'u': 'barye'}},
    # molar flow
    'mol/s':       {'to_SI':  {'f': lambda F: F,                                   'u': 'mol/s'},
                    'to_cgs': {'f': lambda F: F,                                   'u': 'mol/s'}},
    'mol/h':       {'to_SI':  {'f': lambda F: F/3600,                              'u': 'mol/s'},
                    'to_cgs': {'f': lambda F: F/3600,                              'u': 'mol/s'}},
    'mol/d':       {'to_SI':  {'f': lambda F: F/(24*3600),                         'u': 'mol/s'},
                    'to_cgs': {'f': lambda F: F/(24*3600),                         'u': 'mol/s'}},
    'mmol/s':      {'to_SI':  {'f': lambda F: F*1e-3,                              'u': 'mol/s'},
                    'to_cgs': {'f': lambda F: F*1e-3,                              'u': 'mol/s'}},
    'µmol/s':      {'to_SI':  {'f': lambda F: F*1e-6,                              'u': 'mol/s'},
                    'to_cgs': {'f': lambda F: F*1e-6,                              'u': 'mol/s'}},
    'kmol/s':      {'to_SI':  {'f': lambda F: F*1000,                              'u': 'mol/s'},
                    'to_cgs': {'f': lambda F: F*1000,                              'u': 'mol/s'}},
    'kmol/h':      {'to_SI':  {'f': lambda F: F*1000/3600,                         'u': 'mol/s'},
                    'to_cgs': {'f': lambda F: F*1000/3600,                         'u': 'mol/s'}},
    'kmol/d':      {'to_SI':  {'f': lambda F: F*1000/(24*3600),                    'u': 'mol/s'},
                    'to_cgs': {'f': lambda F: F*1000/(24*3600),                    'u': 'mol/s'}},
    # mass
    'kg':          {'to_SI':  {'f': lambda m: m,                                   'u': 'kg'},
                    'to_cgs': {'f': lambda m: m*1000,                              'u': 'g'}},
    'g':           {'to_SI':  {'f': lambda m: m/1000,                              'u': 'kg'},
                    'to_cgs': {'f': lambda m: m,                                   'u': 'g'}},
    'ton':         {'to_SI':  {'f': lambda m: m*1000,                              'u': 'kg'},
                    'to_cgs': {'f': lambda m: m*1000**2,                           'u': 'g'}},
    'lb':          {'to_SI':  {'f': lambda m: m*0.4535924,                         'u': 'kg'},
                    'to_cgs': {'f': lambda m: m*453.592,                           'u': 'g'}},
    # length
    'm':           {'to_SI':  {'f': lambda l: l,                                   'u': 'm'},
                    'to_cgs': {'f': lambda l: l*100,                               'u': 'cm'}},
    'cm':          {'to_SI':  {'f': lambda l: l/100,                               'u': 'm'},
                    'to_cgs': {'f': lambda l: l,                                   'u': 'cm'}},
    'mm':          {'to_SI':  {'f': lambda l: l/1000,                              'u': 'm'},
                    'to_cgs': {'f': lambda l: l/10,                                'u': 'cm'}},
    'µm':          {'to_SI':  {'f': lambda l: l/1e6,                               'u': 'm'},
                    'to_cgs': {'f': lambda l: l/1e4,                               'u': 'cm'}},
    'in':          {'to_SI':  {'f': lambda l: l*0.0254,                            'u': 'm'},
                    'to_cgs': {'f': lambda l: l*2.54,                              'u': 'cm'}},
    'ft':          {'to_SI':  {'f': lambda l: l*0.3048,                            'u': 'm'},
                    'to_cgs': {'f': lambda l: l*30.48,                             'u': 'cm'}},
    # energy
    'J':           {'to_SI':  {'f': lambda E: E,                                   'u': 'J'},
                    'to_cgs': {'f': lambda E: E*1e7,                               'u': 'erg'}},
    'erg':         {'to_SI':  {'f': lambda E: E*1e-7,                              'u': 'J'},
                    'to_cgs': {'f': lambda E: E,                                   'u': 'erg'}},
    # power
    'W':           {'to_SI':  {'f': lambda pwr: pwr,                               'u': 'W'},
                    'to_cgs': {'f': lambda pwr: pwr*1e7,                           'u': 'erg/s'}},
    'kW':          {'to_SI':  {'f': lambda pwr: pwr*1e3,                           'u': 'W'},
                    'to_cgs': {'f': lambda pwr: pwr*1e3*1e7,                       'u': 'erg/s'}},
    'MW':          {'to_SI':  {'f': lambda pwr: pwr*1e6,                           'u': 'W'},
                    'to_cgs': {'f': lambda pwr: pwr*1e6*1e7,                       'u': 'erg/s'}},
    'GW':          {'to_SI':  {'f': lambda pwr: pwr*1e9,                           'u': 'W'},
                    'to_cgs': {'f': lambda pwr: pwr*1e9*1e7,                       'u': 'erg/s'}},
    'erg/s':       {'to_SI':  {'f': lambda pwr: pwr*1e-7,                          'u': 'W'},
                    'to_cgs': {'f': lambda pwr: pwr,                               'u': 'erg/s'}},
    'erg/min':     {'to_SI':  {'f': lambda pwr: pwr/(1e7*60),                      'u': 'W'},
                    'to_cgs': {'f': lambda pwr: pwr/60,                            'u': 'erg/s'}},
    'erg/h':       {'to_SI':  {'f': lambda pwr: pwr/(1e7*3600),                    'u': 'W'},
                    'to_cgs': {'f': lambda pwr: pwr/3600,                          'u': 'erg/s'}},
    'hp':          {'to_SI':  {'f': lambda pwr: pwr*745.7,                         'u': 'W'},
                    'to_cgs': {'f': lambda pwr: pwr*745.7*1e7,                     'u': 'erg/s'}},
    'btu/h':       {'to_SI':  {'f': lambda pwr: pwr*0.29307107,                    'u': 'W'},
                    'to_cgs': {'f': lambda pwr: pwr*0.29307107*1e7,                'u': 'erg/s'}},
    # heat transfer coefficients
    'W/m2/K':      {'to_SI':  {'f': lambda U: U,                                   'u': 'W/m2/K'},
                    'to_cgs': {'f': lambda U: U*1e7/(100**2),                      'u': 'erg/s/cm2/K'}},
    'erg/s/cm2/K': {'to_SI':  {'f': lambda U: U*1e-7*100**2,                       'u': 'W/m2/K'},
                    'to_cgs': {'f': lambda U: U,                                   'u': 'erg/s/cm2/K'}},
    'btu/h/ft2/F': {'to_SI':  {'f': lambda U: U*10.7639*1.8/3.412141633,           'u': 'W/m2/K'},
                    'to_cgs': {'f': lambda U: U*(10.7639*1.8/3.4121)*1e7/(100**2), 'u': 'erg/s/cm2/K'}},
    # density
    'kg/m3':       {'to_SI':  {'f': lambda d: d,                                   'u': 'kg/m3'},
                    'to_cgs': {'f': lambda d: d*1000/(100**3),                     'u': 'g/cm3'}},
    'ton/m3':      {'to_SI':  {'f': lambda d: d*1000,                              'u': 'kg/m3'},
                    'to_cgs': {'f': lambda d: d,                                   'u': 'g/cm3'}},
    'g/cm3':       {'to_SI':  {'f': lambda d: d*(100**3)/1000,                     'u': 'kg/m3'},
                    'to_cgs': {'f': lambda d: d,                                   'u': 'g/cm3'}},
    'g/mL':        {'to_SI':  {'f': lambda d: d*(100**3)/1000,                     'u': 'kg/m3'},
                    'to_cgs': {'f': lambda d: d,                                   'u': 'g/cm3'}},
    'lb/ft3':      {'to_SI':  {'f': lambda d: d*0.453592/0.0283168,                'u': 'kg/m3'},
                    'to_cgs': {'f': lambda d: d/62.428,                            'u': 'g/cm3'}},
    # heat capacity
    'J/mol/K':     {'to_SI':  {'f': lambda C: C,                                   'u': 'J/mol/K'},
                    'to_cgs': {'f': lambda C: C*1e7,                               'u': 'erg/mol/K'}},
    'erg/mol/K':   {'to_SI':  {'f': lambda C: C*1e-7,                              'u': 'J/mol/K'},
                    'to_cgs': {'f': lambda C: C,                                   'u': 'erg/mol/K'}},
    # specific energy
    'J/mol':       {'to_SI':  {'f': lambda e: e,                                   'u': 'J/mol'},
                    'to_cgs': {'f': lambda e: e*1e7,                               'u': 'erg/mol'}},
    'kJ/mol':      {'to_SI':  {'f': lambda e: e*1000,                              'u': 'J/mol'},
                    'to_cgs': {'f': lambda e: e*1000*1e7,                          'u': 'erg/mol'}},
    'kJ/kmol':     {'to_SI':  {'f': lambda e: e,                                   'u': 'J/mol'},
                    'to_cgs': {'f': lambda e: e*1e7,                               'u': 'erg/mol'}},
    'J/kmol':      {'to_SI':  {'f': lambda e: e/1000,                              'u': 'J/mol'},
                    'to_cgs': {'f': lambda e: e*1e7/1000,                          'u': 'erg/mol'}},
    'erg/mol':     {'to_SI':  {'f': lambda e: e*1e-7,                              'u': 'J/mol'},
                    'to_cgs': {'f': lambda e: e,                                   'u': 'erg/mol'}},
    'erg/kmol':    {'to_SI':  {'f': lambda e: e/(1e7*1000),                        'u': 'J/mol'},
                    'to_cgs': {'f': lambda e: e/1000,                              'u': 'erg/mol'}},
    # reaction rate
    'mol/s/kg':    {'to_SI':  {'f': lambda r: r,                                   'u': 'mol/s/kg'},
                    'to_cgs': {'f': lambda r: r/1000,                              'u': 'mol/s/g'}},
    'mol/min/kg':  {'to_SI':  {'f': lambda r: r/60,                                'u': 'mol/s/kg'},
                    'to_cgs': {'f': lambda r: r/(1000*60),                         'u': 'mol/s/g'}},
    'mol/h/kg':    {'to_SI':  {'f': lambda r: r/3600,                              'u': 'mol/s/kg'},
                    'to_cgs': {'f': lambda r: r/(1000*3600),                       'u': 'mol/s/g'}},
    'kmol/h/kg':   {'to_SI':  {'f': lambda r: r*1000/3600,                         'u': 'mol/s/kg'},
                    'to_cgs': {'f': lambda r: r/3600,                              'u': 'mol/s/g'}},
    'mol/s/g':     {'to_SI':  {'f': lambda r: r*1000,                              'u': 'mol/s/kg'},
                    'to_cgs': {'f': lambda r: r,                                   'u': 'mol/s/g'}},
    'mol/min/g':   {'to_SI':  {'f': lambda r: r*1000/60,                           'u': 'mol/s/kg'},
                    'to_cgs': {'f': lambda r: r/60,                                'u': 'mol/s/g'}},
    'mol/h/g':     {'to_SI':  {'f': lambda r: r*1000/3600,                         'u': 'mol/s/kg'},
                    'to_cgs': {'f': lambda r: r/3600,                              'u': 'mol/s/g'}},
    # volumetric flow
    'm3/s':        {'to_SI':  {'f': lambda v: v,                                   'u': 'm3/s'},
                    'to_cgs': {'f': lambda v: v*100**3,                            'u': 'cm3/s'}},
    'cm3/s':       {'to_SI':  {'f': lambda v: v*100**-3,                           'u': 'm3/s'},
                    'to_cgs': {'f': lambda v: v*100,                               'u': 'cm3/s'}},
    # mass flow
    'g/s':         {'to_SI':  {'f': lambda m: m/1000,                              'u': 'kg/s'},
                    'to_cgs': {'f': lambda m: m,                                   'u': 'g/s'}},
    'kg/s':        {'to_SI':  {'f': lambda m: m,                                   'u': 'kg/s'},
                    'to_cgs': {'f': lambda m: m*1000,                              'u': 'g/s'}},
    # velocity
    'm/s':         {'to_SI':  {'f': lambda u: u,                                   'u': 'm/s'},
                    'to_cgs': {'f': lambda u: u*100,                               'u': 'cm/s'}},
    'cm/s':        {'to_SI':  {'f': lambda u: u/100,                               'u': 'm/s'},
                    'to_cgs': {'f': lambda u: u,                                   'u': 'cm/s'}},
}